services:
  - type: web
    name: moodle-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: MOODLE_USERNAME
        value: admin
      - key: MOODLE_PASSWORD
        value: admin123
      - key: MOODLE_EMAIL
        value: admin@example.com
